-- =============================================
-- Seed users: AI Everything Badge Scans - ibrahim-&-haddad
-- Sources: Ibrahim, Haddad. Run after schema.sql.
-- =============================================

-- Ensure new columns exist (for DBs created before schema was updated)
alter table users add column if not exists title text default '';
alter table users add column if not exists company text default '';
alter table users add column if not exists notes text default '';
alter table users add column if not exists priority text default '';
alter table users add column if not exists source text default '';

-- Users from "AI Everything Badge Scans - ibrahim-&-haddad.csv"
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Bassem Refaat', 'bassem@alstudio.ai', '201211430746', 'Co-Founder and CTO', 'Alstudio.ai', 'B2b client (Dina was representing them in Supernova)', 'High', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Menna Eltobgi', 'menna.el-tobgi@sprints.ai', '201226638334', 'Senior Communication Specialist', 'Sprints AI', 'اول b2b client بأمر الله', 'High', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Ayman Bazaraa', 'ayman.bazaraa@sprints.ai', '201001348355', 'CEO', 'SPRINTS', 'اول b2b client بأمر الله', 'High', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Ibrahim Rashid', 'ibrahim.rashid@speed.com.eg', '201118383818', 'Business Development Associate Director', 'SPEED Co.', 'content creator ع الماشي - هيموت ويجرب ابو ببلاش', 'Medium', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Akram Elkallal', 'akram.afk@gmail.com', '201222355497', 'CEO', 'Geniprocess International', 'User & Angle Investor', 'High', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Alyaa Hassan', 'alyaa_ali@hotmail.com', '201006204162', 'General Manager', 'Saden solutions', 'هتموت وتجرب دلوقتي حالا', 'High', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Shayma Shehab', '-', '1026215220', 'مذيعة', 'قناة الناس', '', 'High', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Alia Attia', 'AliaAttiaFlower4ever@aucegypt.edu', '201000696488', 'Instructor', 'The American University in Cairo (AUC)', 'voice over artist (عميل مهم ومتحمسه تجرب)', 'High', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Bishoy Michel', 'bishoy.michel@scribeme-ai.com', '201288122656', 'COO', 'ScribeMe', 'بيعمل محتوى تقريبا ومهتم اوي يجرب', 'Medium', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Amr Awad', 'Amrsayed55082@gmail.com', '201004644176', 'account manager', 'stallion', 'عايزني احضر معرض الدوحة عندهم حاجات لذيذة', 'Medium', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Maged Tammam', 'maged.tammam@ca-egypt.com', '201066615662', 'CIO', 'Credit Agricole Bank', 'بيعملوا فيديوهات للبنك', 'High', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Youssef Adris', 'yousefadris@studiohawa.ai', '10022212433', 'Founder | Creative Director', 'Studio Hawa', 'هيموت ويجرب ال tool دي عشان محتاجها اوي ف شغله', 'High', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Ahmed Mohamed', 'info@thetransformix.com', '01207227165 01207172596', '-', 'Transformik', 'نديهم نسخة يجربوا ويدونا نسخة نجرب بيدوك insights ازاي تحسن ال business بتاعك عن طريق شوية scrabing', 'High', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Elnaser Abdelwahab', 'elnaser@hotmail.com', '201020161939', 'Gm', 'Dbcon', 'Friend of Dr Fouad Dehlawi', 'High', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Dr Fouad Dehlawi', 'fdehlawi@gmail.com', '966505615479', 'Associate Professor', 'King Abdul Aziz University', 'Saudi content creators (User & Investor)', 'High', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Mahmoud Farrag', 'mahmoudfarrag.eg@gmail.com', '201111005446', 'Embedded Hardware Engineer', 'Fruitful Solutions', 'اخوه شغال blogger', 'Medium', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('El-Fatih El-Frazdag', 'fatihfrazdag_@hotmail.com', '201553577065', '3D modeler', 'Hash Solutions', 'promising content creators', 'Medium', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Yassir Abdulhalim', 'yassir@hsmea.net', '201558077117', 'Art Director', 'Hash Solution', 'promising content creators', 'Medium', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Eman Mohsen', 'skilltech@eman-mohsen.com', '1002836415', 'Founder', 'Skill Tech', 'motivated content creator', 'High', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Mahmoud Fahmy', 'fahmy@coursetopia.net', '1111151959', 'CEO', 'CourseTopia', '', 'High', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Magy El Banhawy', 'mbanhawy2004@gmail.com', '201062309948', 'Robotics Engineer', 'New Mansoura university', 'Robotics academy (they make content)', 'Medium', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Youssuf Khattab', 'y.khattab@cloudinfinity.co', '201040003069', 'Business development', 'Cloudinfinity', 'content creator', 'Medium', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Mina Elgabalawy', 'el_gabalawy@hotmail.com', '201222191832', 'Business development director', 'Private', 'exporting medicine (will use it in marketing)', 'Medium', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Mehul Nahar', 'mehul.nahar@mindcrewtech.com', '91 96502 66977', 'Founder', 'MindCrew Technologies', 'sales & marketing agency', 'Medium', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Fouad Elshazly', 'info@foxestechnology.com', '201153855556', 'CEO', 'Foxes Technology LLC', 'Digital transformation', 'Medium', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Noureldin Zoghly', 'nour@scaleby.ai', '201000345389', 'CPO', 'Scale by AI', '', 'High', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Muhammad Taufiq', 'muhammadtaufiq636@gmail.com', '60145178670', 'Business Development', 'Mirfalah Technologies Sdn Bhd', 'شباب ماليزي عنده فيديوهات عايز يجرب عليها', 'Low', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Aliff Amiruddin', 'aliffamir@mirfalah.my', '60199654994', 'Director', 'Mirfalah Technologies Sdn Bhd', 'شباب ماليزي عنده فيديوهات عايز يجرب عليها', 'Low', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Mohamed Selim', 'mragab0@hotmail.com', '1000342499', 'Division Deputy Manager', 'National Bank of Egypt', 'اخو مراته بيعمل حلول صناعية وعنده ميديا', 'Medium', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Mohamed Elbadry', 'melbadry@korastats.com', '201112272714', 'CEO', 'KoraStats', '', 'High', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Marina Youssry', 'marina@flat6labs.com', '201286192320', 'Senior Social Media Specialist', 'Flat6Labs', '', 'High', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Sherif Hassan', 'sherief@flat6labs.com', '201020006315', 'Flat6Labs Marketing Director', 'Flat6Labs', '', 'High', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Waleed El Naggar', 'w.elnagar@o2-mediagroup.com', '201098181184', 'IT Manager', 'O2 media for Information Technology', '', 'High', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Mary Nabil', 'marynabil85@gmail.com', '201205801985', 'Senior Graphic Designer', 'O2 Media for Information Technology', '', 'High', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Waleed Essam', 'waleedessam77@gmail.com', '201127159987', 'Marketing Expert', 'O2 Media', '', 'High', 'Ibrahim');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('George Sabry', '-', '201006133380', 'Marketing Director Filgoal', 'Filgoal', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Heba Gamal', '-', '201117135153', 'AI engineer', '', 'She is an ai engineer can help us in feedback not a user', 'Low', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Asmaa Mohamed', '-', '201103956200', 'Marketing lead', '', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Karim Ashraf', '-', '201111861068', '', '', 'Has Marketing team', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Amir Sameh', 'ameersameh@gmail.com', '201210894309', '', '', '', 'Low', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Ahmed Osman', '-', '201111670201', '', '', '', 'Low', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Rami', '-', '201222462125', '', '', '', 'Low', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Hazem El Snosy', '-', '201001795123', '', '', 'Marketing Agency', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Ahmed Ezzat', '-', '201100228705', '', '', '', 'Low', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Mohamed Adel', '-', '201011269423', '', '', 'real user for that case', 'Low', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Ziad Ahmed', '-', '201507030962', 'video editor', '', '', 'Medium', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Mohamed Emam', '-', '201030012331', '', '', '', 'Medium', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Ansam', '-', '201011489397', '', '', '', 'Medium', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Noury Medhat', '-', '201004436819', 'Head of Design & Media at Business بالعربي', '', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Ahmed Badr', '-', '201123123132', 'Business بالعربي', '', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Jagan Redington', '-', '201151280785', '', '', '', 'Low', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Mohand Hesham', '-', '201119278504', '', '', '- loay hesham اخوه عنده قناه يوتيوب كبيره', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Ibrahim Raslan', '-', '201111792228', 'legal content creator', '', '', 'Medium', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Mohamed Raafat', 'info@tootmusic.ai', '201061615904', 'CTO', 'TOOT Music', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Maida Hussen', 'maidahussen79@gmail.com', '201281667714', 'dr engineer', 'stce', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Amr Atef', 'aatef@cg.com.sa', '201030373780', 'Manager', 'EI Labs', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Ahmad Meheisen', 'ahmad@meheisen.com', '201002040080', 'none', 'none', '', 'Low', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Ahmed Abdelbaky', 'ahmedabdelbaky11@gmail.com', '201008130003', 'Marketing manager', 'Workshop media productions', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Amr Elmawardy', 'amr.elmawardy94@gmail.com', '201065442884', 'Founder and Project Lead', 'NutrixPOS', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Joe Khayat', 'joegkhayat@gmail.com', '201141422223', 'CEO', 'Ototop', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Hussien Elsayed', 'helsaid@trenddc.com', '201098300547', 'Research and Development Director', 'Trend', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Ezzeldin Osman', 'ceo@aigislaw.ai', '201111105001', 'CEO', 'Aigis Technology', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Alaa Alaa', 'masstrad2@gmail.com', '201223590672', 'Manger', 'Master', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Maged Mohamed', 'magedrawash@live.com', '201017507513', 'Founder', 'eDariba', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Mostafa Mohamed', 'mostafa.m.alf.r@gmail.com', '201099129550', 'product manager', 'edariba', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Asmaa Mourad', 'asmaa.hmourad@gmail.com', '201009676592', 'Regional Business Innovation and Partnerships Manager', 'Iskraemeco By Elsweedy Electric', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Ziad El Marsafawy', 'ziad@fernsystemsai.com', '201006556897', 'Founder', 'Fern Systems AI', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Andrew Luke', 'andrew.labib2017@gmail.com', '201062086727', 'Cyber Security Consultant', 'Intelliga AI', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Mazen Elmadawy', 'mazen.elmaadawi@mention-ed.com', '201205533217', 'Business development', 'Xlra', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Asmaa Mohamed', 'asmaalogisticnuts@gmail.com', '201011881502', 'QA', 'logistic nuts', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Tamer Elshafey', 'elshafey.tamer@gmail.com', '201063335517', 'General Manager', 'Teck Bokra', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Marwa Magdy', 'marwamagdy2050@gmail.com', '201096614967', 'Digital marketing lead', 'Troya marketing', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Hassan Sami', 'hassan.sami19857@outlook.com', '201155050775', 'Senior account manager', 'Troya marketing agency', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Amr Azazy', 'amr.ceiorg@gmail.com', '201017625006', 'GRC Team Leader', 'CAMPUS', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Ahmed Mostafa', 'ahmedmo1286631@gmail.com', '201143069909', 'Vulnerability analyst and penetration tester', 'Safeco tech', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Hesham Abdallah', 'hesham@payiano.com', '201110540756', 'CEO', 'Payiano', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Abdelrahman Mostafa', 'iabdozzg@gmail.com', '201001910102', 'IT Specialist', 'It-why?', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Mohamad Shabrawy', 'mohamadsheriff165@gmail.com', '201141833526', 'media development agency', '', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Ese Okotie', 'ese_okotie2003@yahoo.co', '2348069412078', 'CEO', 'primetek', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Hossam Eldin', 'herr.simsim@gmail.com', '201008750700', 'Teacher', 'Deu', '', 'Low', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Ahmed Amin', 'info@tawaasol.com', '201101444639', 'Founder at Tawaasol', 'Tawaasol', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Mostafa Soliman', 'mostafa.soliman2005@gmail.com', '201000170715', 'Ceo', 'Quest', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Asmaa', '-', '201115212756', '', '', '', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Ziad Abozaid', '-', '201552444488', 'Co-Founder at Middl-men', '', 'https://www.linkedin.com/search/results/all/?keywords=Ziad%20Abozaid&origin=GLOBAL_SEARCH_HEADER', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Mahmoud Elgaml', '-', '201000272551', 'Results-Driven Ecommerce Expert', '', 'https://www.linkedin.com/in/mahmoud-elgaml-7a3376a6/', 'High', 'Haddad');
insert into users (display_name, email, phone, title, company, notes, priority, source) values ('Peter Ibrahim', '-', '201285288028', 'Edutech', '', 'https://www.linkedin.com/in/peter-ibrahim-kamal/', 'High', 'Haddad');
